### ISSUE TITLE
Down nodes prevent some kubectl commands.

### ISSUE THREAD

**Issue by gfr10598** [m-lab/k8s-support#141] opened 2019-03-19 19:02 UTC
Some nodes in our system may become unreachable.  They should time out and be deleted from k8s.  Otherwise, some kubectl commands, like delete, may fail when there are unreachable nodes, and block anything else from happening.

**Comment by nkinkade** [comment] 2019-03-22 19:02
To clarify, kubectl don't just generally stop working for some commands in these cases. To be specific, you may not be able to delete a pod (gracefully) that is scheduled on an unresponsive node. You _may_ be able to delete it by passing `--force --grace-period=0` to the delete command. And you can always get rid of all the pods on the unresponsive node by manually deleting the node.

There is no mechanism in k8s, that I know of, that will time-out a node and delete it. The only mechanism that approaches this is cloud-provider specific, and will _only_ delete the node if k8s can verify through the cloud-provider API that the VM was actually deleted. In other cases, it doesn't know what to do with the node, and will just leave it in alone until it comes back, or an operator takes manual action.

If we do want something to automatically delete unresponsive nodes (and I'm not sure we want this), would be to write some sort of script/daemon that monitors for this and takes action on our behalf.

**Comment by pboothe** [comment] 2019-03-25 16:52
Workaround is to 
- use `kubectl apply` instead of `kubectl delete`
- delete the node if you really need to use `kubectl delete`

**Comment by nkinkade** [comment] 2019-10-31 20:10
@pboothe, @gfr: Do either of you still consider this an issue/bug? This is documented and intentional k8s behavior.  We may _possibly_ want some sort of service running in the cluster that monitors for nodes in a NotReady state, perhaps deleting them after a certain period, but I would think that is unrelated to this issue.

**Comment by pboothe** [comment] 2019-10-31 21:02
If it is intentional k8s behavior, then it is not a bug, it is instead something we need to get used to.

**Comment by nkinkade** [comment] 2019-10-31 21:09
[It is by design](https://kubernetes.io/docs/concepts/architecture/nodes/#condition):

> In versions of Kubernetes prior to 1.5, the node controller would force delete these unreachable pods from the apiserver. However, in 1.5 and higher, the node controller does not force delete pods until it is confirmed that they have stopped running in the cluster. You can see the pods that might be running on an unreachable node as being in the Terminating or Unknown state. In cases where Kubernetes cannot deduce from the underlying infrastructure if a node has permanently left a cluster, the cluster administrator may need to delete the node object by hand. Deleting the node object from Kubernetes causes all the Pod objects running on the node to be deleted from the apiserver, and frees up their names.

I believe we will just have to live with the fact that pods on down nodes will continue to be present in the cluster, and may block rollouts, rolling reboots, etc. We'll need to find some other way to deal with these scenarios, perhaps with alerts, since we don't really want pods in the cluster for nodes that are known to be down.

Please close this issue if you are satisfied that this is expected behavior and not a bug that needs resolving.

**Closed** 2019-11-01 13:45 UTC
Labels: P2, backlog
